oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: OAuthServerBundle:Security:login }

oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: OAuthServerBundle:Security:loginCheck }