scout_core:
    resource: "@ScoutCoreBundle/Resources/config/routing.yml"
    prefix:   /

beacon_event:
    resource: "@BeaconEventBundle/Resources/config/routing.yml"
    prefix:   /

beacon:
    resource: "@BeaconBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

scout:
    resource: "@ScoutBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
