scout_homepage:
    path:     /
    defaults: { _controller: ScoutBundle:Default:index }

login:
    path: /login
    defaults: { _controller: ScoutBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

