services:
    locale.service:
        class: Buoy\LocaleBundle\Service\LocaleService
        arguments: [@doctrine.orm.entity_manager]
    geocoder.adapter:
        class:  Geocoder\HttpAdapter\CurlHttpAdapter
    geocoder.address:
        class:  Geocoder\Provider\GoogleMapsProvider
        arguments: [@geocoder.adapter]
    geocoder.ip:
        class:  Geocoder\Provider\FreeGeoIpProvider
        arguments: [@geocoder.adapter]